### PR TITLE
Fixing issue of showing help for the wrong alias

### PR DESCRIPTION
**Pull request by oarrabi**
Fixes issue #61

### CODE REVIEW

**Comment by goyox86** [comment]
👍 :shipit: on 💚

**Comment by amg1976** [comment]
Nice!

**Comment by oarrabi** [comment]
@goyox86 @amg1976 
I also reworked some messages in the generator

https://github.com/oarrabi/Guaka-Generator/pull/5

**Comment by oarrabi** [comment]
Finally!!

**Pull request merged**
